// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LocationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface LocationRoot : GPBRootObject
@end

#pragma mark - Location

typedef GPB_ENUM(Location_FieldNumber) {
  Location_FieldNumber_AccessToken = 1,
  Location_FieldNumber_CdType = 2,
  Location_FieldNumber_ClientId = 3,
  Location_FieldNumber_ConnectUser = 4,
  Location_FieldNumber_Direction = 5,
  Location_FieldNumber_Latitude = 6,
  Location_FieldNumber_Longitude = 7,
  Location_FieldNumber_OrderId = 8,
  Location_FieldNumber_Speed = 9,
  Location_FieldNumber_Timestamp = 10,
  Location_FieldNumber_TravelMile = 11,
  Location_FieldNumber_Type = 12,
};

/**
 *
 * accessToken = "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxODQwMDAwMDAwOCIsInV1aWQiOiIwN0Q3NEJFQTA2QUU0RTczODlDQzYyN0MxRTBCRjAxMiIsIm5pY2tOYW1lIjoiZHJpdmVyLTA4IiwidXNlckhlYWRlciI6ImNhcnBsdXNnby1pbmZvLWltZy8yMDE5LTA4LTI3LzQ3N2NhYzgzMTNlZDk4YjNmYmVmYzQ0ZGY2MzA1ZjI1LnBuZyIsInNjb3BlcyI6WyJST0xFX0FDQ0VTU19UT0tFTiJdLCJpc3MiOiJodHRwOi8vd3d3LnJpaHVpc29mdC5jb20iLCJpYXQiOjE1NjgwMTQ5NzUsImV4cCI6MTU2ODYxOTc3NX0.kTQ5Ibg32kGTd8JoYwUNE6tIxq_09AuxVtgJeuJCt_EuCC77-pWxJPtvAh34dt-E4_izcIJXhuTugSGxD02JhA";
 * cdType = 2;
 * clientId = 5cb41eec2d70cc086f5b65da;
 * connectUser = 5d5ca149aacbc02661ca27bb;
 * direction = 2;
 * expTime2 = "";
 * latitude = "30.199544680748";
 * longitude = "120.27409366925";
 * orderId = 5d76028e7754cb4f2ddb5eb9;
 * speed = "0.18106";
 * timestamp = 1568015000468;
 * travelMile = 0;
 * type = LOCATION;
 **/
@interface Location : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cdType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *direction;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) float speed;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) float travelMile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
