// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DrstatusReq;
@class DrstatusRes;
@class DrstatusWebReq;
@class LocationReq;
@class LocationRes;
@class OrderAssignReq;
@class OrderAssignRes;
@class OrderAutoCostReq;
@class OrderAutoCostRes;
@class OrderCancelReq;
@class OrderCancelRes;
@class OrderDriverArriveReq;
@class OrderDriverArriveRes;
@class OrderDriverPickUpReq;
@class OrderDriverPickUpRes;
@class OrderEndReq;
@class OrderEndRes;
@class OrderPayOkReq;
@class OrderPayOkRes;
@class OrderPrMissReq;
@class OrderPrMissRes;
@class OrderRecEndReq;
@class OrderRecEndRes;
@class OrderRecReq;
@class OrderRecRes;
@class OrderReq;
@class OrderRes;
@class OrderStartReq;
@class OrderStartRes;
@class Ping;
@class Pong;
@class RegisterReq;
@class RegisterRes;
@class UserTrackReq;
@class UserTrackRes;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MSG_TYPE

/** 消息类型 */
typedef GPB_ENUM(MSG_TYPE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MSG_TYPE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 客户端心跳请求 */
  MSG_TYPE_Ping = 0,

  /** 客户端传输位置信息 */
  MSG_TYPE_LocationReq = 2,

  /** 客户端注册channel */
  MSG_TYPE_RegisterReq = 3,

  /** 客户端内部使用 */
  MSG_TYPE_UsertrackReq = 4,

  /** 车辆状态推送消息 是否有乘客，是否接单 */
  MSG_TYPE_DrstatusReq = 5,

  /** 客户下预约单 */
  MSG_TYPE_OrderReq = 16,

  /** 司机结束行程 */
  MSG_TYPE_OrderEndReq = 17,

  /** 司机接单（即时单/预约单） */
  MSG_TYPE_OrderRecReq = 18,

  /** 乘客取消订单 */
  MSG_TYPE_OrderCancelReq = 19,

  /** 指派司机 (即时单) */
  MSG_TYPE_OrderAssignReq = 20,

  /** 司机已达到 */
  MSG_TYPE_OrderDriverArriveReq = 21,

  /** 司机已出发 */
  MSG_TYPE_OrderDriverPickupReq = 22,

  /** 订单被接-预约单 */
  MSG_TYPE_OrderRecEndReq = 23,

  /** 开始行程 */
  MSG_TYPE_OrderStartReq = 24,

  /** 司机到达，开始计算等待时长费 */
  MSG_TYPE_OrderAutoCostReq = 25,

  /** 订单支付成功 */
  MSG_TYPE_OrderPayokReq = 32,

  /** 无司机响应 */
  MSG_TYPE_OrderPrmissReq = 33,

  /** 司机状态 */
  MSG_TYPE_DrStatusWebReq = 34,

  /** 服务端心跳响应 */
  MSG_TYPE_Pong = 1,

  /** 位置信息响应 */
  MSG_TYPE_LocationRes = 256,

  /** 注册响应 */
  MSG_TYPE_RegisterRes = 257,

  /** 客户端内部使用 */
  MSG_TYPE_UsertrackRes = 258,

  /** 车辆状态推送消息 是否有乘客，是否接单 */
  MSG_TYPE_DrstatusRes = 259,

  /** 客户下预约单 */
  MSG_TYPE_OrderRes = 260,

  /** 司机结束行程 */
  MSG_TYPE_OrderEndRes = 261,

  /** 司机接单（即时单/预约单） */
  MSG_TYPE_OrderRecRes = 262,

  /** 乘客取消订单 */
  MSG_TYPE_OrderCancelRes = 263,

  /** 指派司机 (即时单) */
  MSG_TYPE_OrderAssignRes = 264,

  /** 司机已达到 */
  MSG_TYPE_OrderDriverArriveRes = 265,

  /** 司机已出发 */
  MSG_TYPE_OrderDriverPickupRes = 272,

  /** 订单被接-预约单 */
  MSG_TYPE_OrderRecEndRes = 273,

  /** 开始行程 */
  MSG_TYPE_OrderStartRes = 274,

  /** 司机到达，开始计算等待时长费 */
  MSG_TYPE_OrderAutoCostRes = 275,

  /** 订单支付成功 */
  MSG_TYPE_OrderPayokRes = 276,

  /** 无司机响应 */
  MSG_TYPE_OrderPrmissRes = 277,
};

GPBEnumDescriptor *MSG_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MSG_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum CLIENT_TYPE

typedef GPB_ENUM(CLIENT_TYPE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CLIENT_TYPE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 未知 */
  CLIENT_TYPE_Unkown = 0,

  /** 乘客 */
  CLIENT_TYPE_Passenger = 1,

  /** 司机 */
  CLIENT_TYPE_Driver = 2,

  /** Travel 服务端服务 */
  CLIENT_TYPE_Travel = 3,
};

GPBEnumDescriptor *CLIENT_TYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CLIENT_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum RET_CODE

typedef GPB_ENUM(RET_CODE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  RET_CODE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 成功 */
  RET_CODE_Success = 0,

  /** 失败 */
  RET_CODE_Failure = 1,
};

GPBEnumDescriptor *RET_CODE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RET_CODE_IsValidValue(int32_t value);

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - Ping

/**
 * 客户端请求ping
 **/
@interface Ping : GPBMessage

@end

#pragma mark - Pong

/**
 * 服务端返回pong
 **/
@interface Pong : GPBMessage

@end

#pragma mark - LocationReq

typedef GPB_ENUM(LocationReq_FieldNumber) {
  LocationReq_FieldNumber_Longitude = 1,
  LocationReq_FieldNumber_Latitude = 2,
  LocationReq_FieldNumber_Speed = 3,
  LocationReq_FieldNumber_Direction = 4,
  LocationReq_FieldNumber_OrderId = 5,
  LocationReq_FieldNumber_ConnectUser = 6,
  LocationReq_FieldNumber_TravelMile = 7,
  LocationReq_FieldNumber_TravelAmount = 8,
  LocationReq_FieldNumber_ExpTime2 = 9,
  LocationReq_FieldNumber_Timestamp = 10,
};

/**
 * 定位信息
 **/
@interface LocationReq : GPBMessage

/** 经度 */
@property(nonatomic, readwrite) double longitude;

/** 纬度 */
@property(nonatomic, readwrite) double latitude;

/** 速度 */
@property(nonatomic, readwrite) double speed;

/** 方向 */
@property(nonatomic, readwrite) double direction;

/** 订单ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

/** 发送给对方的clientId */
@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

/** 里程（米） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *travelMile;

/** 里程实时价格（元） */
@property(nonatomic, readwrite, copy, null_resettable) NSString *travelAmount;

/** 预计还剩多少分钟到达 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *expTime2;

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - LocationRes

typedef GPB_ENUM(LocationRes_FieldNumber) {
  LocationRes_FieldNumber_Longitude = 1,
  LocationRes_FieldNumber_Latitude = 2,
  LocationRes_FieldNumber_Speed = 3,
  LocationRes_FieldNumber_Direction = 4,
  LocationRes_FieldNumber_TravelMile = 5,
  LocationRes_FieldNumber_TravelAmount = 6,
  LocationRes_FieldNumber_ExpTime2 = 7,
  LocationRes_FieldNumber_OrderId = 8,
  LocationRes_FieldNumber_Timestamp = 9,
};

@interface LocationRes : GPBMessage

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double speed;

@property(nonatomic, readwrite) double direction;

@property(nonatomic, readwrite, copy, null_resettable) NSString *travelMile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *travelAmount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *expTime2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - RegisterReq

typedef GPB_ENUM(RegisterReq_FieldNumber) {
  RegisterReq_FieldNumber_Token = 1,
};

@interface RegisterReq : GPBMessage

/** 用于客户端校验 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - RegisterRes

@interface RegisterRes : GPBMessage

@end

#pragma mark - UserTrackReq

@interface UserTrackReq : GPBMessage

@end

#pragma mark - UserTrackRes

@interface UserTrackRes : GPBMessage

@end

#pragma mark - DrstatusReq

typedef GPB_ENUM(DrstatusReq_FieldNumber) {
  DrstatusReq_FieldNumber_OnOffStatus = 1,
  DrstatusReq_FieldNumber_Status = 2,
};

@interface DrstatusReq : GPBMessage

@property(nonatomic, readwrite) uint32_t onOffStatus;

@property(nonatomic, readwrite) uint32_t status;

@end

#pragma mark - DrstatusRes

typedef GPB_ENUM(DrstatusRes_FieldNumber) {
  DrstatusRes_FieldNumber_OnOffStatus = 1,
  DrstatusRes_FieldNumber_Status = 2,
  DrstatusRes_FieldNumber_Timestamp = 3,
};

@interface DrstatusRes : GPBMessage

@property(nonatomic, readwrite) uint32_t onOffStatus;

@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - OrderReq

typedef GPB_ENUM(OrderReq_FieldNumber) {
  OrderReq_FieldNumber_StartAdd = 1,
  OrderReq_FieldNumber_EndAdd = 2,
  OrderReq_FieldNumber_OrderType2 = 3,
  OrderReq_FieldNumber_StartLatitude = 4,
  OrderReq_FieldNumber_StartLongitude = 5,
  OrderReq_FieldNumber_OrderId = 6,
  OrderReq_FieldNumber_EndLatitude = 7,
  OrderReq_FieldNumber_EndLongitude = 8,
};

@interface OrderReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite) uint32_t orderType2;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) double endLatitude;

@property(nonatomic, readwrite) double endLongitude;

@end

#pragma mark - OrderRes

typedef GPB_ENUM(OrderRes_FieldNumber) {
  OrderRes_FieldNumber_StartAdd = 1,
  OrderRes_FieldNumber_EndAdd = 2,
  OrderRes_FieldNumber_OrderType2 = 3,
  OrderRes_FieldNumber_StartLatitude = 4,
  OrderRes_FieldNumber_StartLongitude = 5,
  OrderRes_FieldNumber_OrderId = 6,
  OrderRes_FieldNumber_EndLatitude = 7,
  OrderRes_FieldNumber_EndLongitude = 8,
};

@interface OrderRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite) uint32_t orderType2;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) double endLatitude;

@property(nonatomic, readwrite) double endLongitude;

@end

#pragma mark - OrderEndReq

typedef GPB_ENUM(OrderEndReq_FieldNumber) {
  OrderEndReq_FieldNumber_OrderId = 1,
  OrderEndReq_FieldNumber_StartTime = 2,
  OrderEndReq_FieldNumber_Time = 3,
  OrderEndReq_FieldNumber_Distance = 4,
  OrderEndReq_FieldNumber_Cost = 5,
  OrderEndReq_FieldNumber_ConnectUser = 6,
};

@interface OrderEndReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t startTime;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) double distance;

@property(nonatomic, readwrite) double cost;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderEndRes

typedef GPB_ENUM(OrderEndRes_FieldNumber) {
  OrderEndRes_FieldNumber_OrderId = 1,
  OrderEndRes_FieldNumber_StartTime = 2,
  OrderEndRes_FieldNumber_Time = 3,
  OrderEndRes_FieldNumber_Distance = 4,
  OrderEndRes_FieldNumber_Cost = 5,
  OrderEndRes_FieldNumber_ConnectUser = 6,
};

@interface OrderEndRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t startTime;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) double distance;

@property(nonatomic, readwrite) double cost;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderRecReq

typedef GPB_ENUM(OrderRecReq_FieldNumber) {
  OrderRecReq_FieldNumber_OrderId = 1,
  OrderRecReq_FieldNumber_Timestamp = 2,
  OrderRecReq_FieldNumber_FromUser = 3,
  OrderRecReq_FieldNumber_Longitude = 4,
  OrderRecReq_FieldNumber_Latitude = 5,
  OrderRecReq_FieldNumber_OrderType = 6,
};

@interface OrderRecReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) uint32_t orderType;

@end

#pragma mark - OrderRecRes

typedef GPB_ENUM(OrderRecRes_FieldNumber) {
  OrderRecRes_FieldNumber_OrderId = 1,
  OrderRecRes_FieldNumber_Timestamp = 2,
  OrderRecRes_FieldNumber_FromUser = 3,
  OrderRecRes_FieldNumber_Longitude = 4,
  OrderRecRes_FieldNumber_Latitude = 5,
  OrderRecRes_FieldNumber_OrderType = 6,
};

@interface OrderRecRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) uint32_t orderType;

@end

#pragma mark - OrderCancelReq

typedef GPB_ENUM(OrderCancelReq_FieldNumber) {
  OrderCancelReq_FieldNumber_OrderId = 1,
  OrderCancelReq_FieldNumber_Time = 2,
  OrderCancelReq_FieldNumber_OrderType = 3,
  OrderCancelReq_FieldNumber_FromUser = 4,
  OrderCancelReq_FieldNumber_Role = 5,
};

@interface OrderCancelReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) uint32_t orderType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;

@property(nonatomic, readwrite) uint32_t role;

@end

#pragma mark - OrderCancelRes

typedef GPB_ENUM(OrderCancelRes_FieldNumber) {
  OrderCancelRes_FieldNumber_OrderId = 1,
  OrderCancelRes_FieldNumber_Time = 2,
  OrderCancelRes_FieldNumber_OrderType = 3,
  OrderCancelRes_FieldNumber_FromUser = 4,
  OrderCancelRes_FieldNumber_Role = 5,
};

@interface OrderCancelRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) uint32_t orderType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUser;

@property(nonatomic, readwrite) uint32_t role;

@end

#pragma mark - OrderAssignReq

typedef GPB_ENUM(OrderAssignReq_FieldNumber) {
  OrderAssignReq_FieldNumber_StartAdd = 1,
  OrderAssignReq_FieldNumber_EndAdd = 2,
  OrderAssignReq_FieldNumber_OrderId = 3,
  OrderAssignReq_FieldNumber_Time = 4,
  OrderAssignReq_FieldNumber_Content = 5,
  OrderAssignReq_FieldNumber_ConnectUser = 6,
  OrderAssignReq_FieldNumber_StartLatitude = 7,
  OrderAssignReq_FieldNumber_StartLongitude = 8,
  OrderAssignReq_FieldNumber_EndLatitude = 9,
  OrderAssignReq_FieldNumber_EndLongitude = 10,
};

@interface OrderAssignReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@property(nonatomic, readwrite) double endLatitude;

@property(nonatomic, readwrite) double endLongitude;

@end

#pragma mark - OrderAssignRes

typedef GPB_ENUM(OrderAssignRes_FieldNumber) {
  OrderAssignRes_FieldNumber_StartAdd = 1,
  OrderAssignRes_FieldNumber_EndAdd = 2,
  OrderAssignRes_FieldNumber_OrderId = 3,
  OrderAssignRes_FieldNumber_Time = 4,
  OrderAssignRes_FieldNumber_Content = 5,
  OrderAssignRes_FieldNumber_ConnectUser = 6,
  OrderAssignRes_FieldNumber_StartLatitude = 7,
  OrderAssignRes_FieldNumber_StartLongitude = 8,
  OrderAssignRes_FieldNumber_EndLatitude = 9,
  OrderAssignRes_FieldNumber_EndLongitude = 10,
};

@interface OrderAssignRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@property(nonatomic, readwrite) double startLatitude;

@property(nonatomic, readwrite) double startLongitude;

@property(nonatomic, readwrite) double endLatitude;

@property(nonatomic, readwrite) double endLongitude;

@end

#pragma mark - OrderDriverArriveReq

typedef GPB_ENUM(OrderDriverArriveReq_FieldNumber) {
  OrderDriverArriveReq_FieldNumber_OrderId = 1,
  OrderDriverArriveReq_FieldNumber_Time = 2,
  OrderDriverArriveReq_FieldNumber_ConnectUser = 3,
};

@interface OrderDriverArriveReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderDriverArriveRes

typedef GPB_ENUM(OrderDriverArriveRes_FieldNumber) {
  OrderDriverArriveRes_FieldNumber_OrderId = 1,
  OrderDriverArriveRes_FieldNumber_Time = 2,
  OrderDriverArriveRes_FieldNumber_ConnectUser = 3,
};

@interface OrderDriverArriveRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderDriverPickUpReq

typedef GPB_ENUM(OrderDriverPickUpReq_FieldNumber) {
  OrderDriverPickUpReq_FieldNumber_OrderId = 1,
  OrderDriverPickUpReq_FieldNumber_Time = 2,
  OrderDriverPickUpReq_FieldNumber_ConnectUser = 3,
};

@interface OrderDriverPickUpReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderDriverPickUpRes

typedef GPB_ENUM(OrderDriverPickUpRes_FieldNumber) {
  OrderDriverPickUpRes_FieldNumber_OrderId = 1,
  OrderDriverPickUpRes_FieldNumber_Time = 2,
  OrderDriverPickUpRes_FieldNumber_ConnectUser = 3,
};

@interface OrderDriverPickUpRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderRecEndReq

typedef GPB_ENUM(OrderRecEndReq_FieldNumber) {
  OrderRecEndReq_FieldNumber_OrderId = 1,
  OrderRecEndReq_FieldNumber_OrderType = 2,
  OrderRecEndReq_FieldNumber_Timestamp = 3,
};

@interface OrderRecEndReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint32_t orderType;

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - OrderRecEndRes

typedef GPB_ENUM(OrderRecEndRes_FieldNumber) {
  OrderRecEndRes_FieldNumber_OrderId = 1,
  OrderRecEndRes_FieldNumber_OrderType = 2,
  OrderRecEndRes_FieldNumber_Timestamp = 3,
};

@interface OrderRecEndRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint32_t orderType;

@property(nonatomic, readwrite) uint64_t timestamp;

@end

#pragma mark - OrderStartReq

typedef GPB_ENUM(OrderStartReq_FieldNumber) {
  OrderStartReq_FieldNumber_OrderId = 1,
  OrderStartReq_FieldNumber_Time = 2,
  OrderStartReq_FieldNumber_ConnectUser = 3,
};

@interface OrderStartReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderStartRes

typedef GPB_ENUM(OrderStartRes_FieldNumber) {
  OrderStartRes_FieldNumber_OrderId = 1,
  OrderStartRes_FieldNumber_Time = 2,
  OrderStartRes_FieldNumber_ConnectUser = 3,
};

@interface OrderStartRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderAutoCostReq

typedef GPB_ENUM(OrderAutoCostReq_FieldNumber) {
  OrderAutoCostReq_FieldNumber_ConnectUser = 1,
  OrderAutoCostReq_FieldNumber_OrderId = 2,
  OrderAutoCostReq_FieldNumber_PassengerId = 3,
};

@interface OrderAutoCostReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passengerId;

@end

#pragma mark - OrderAutoCostRes

typedef GPB_ENUM(OrderAutoCostRes_FieldNumber) {
  OrderAutoCostRes_FieldNumber_ConnectUser = 1,
  OrderAutoCostRes_FieldNumber_OrderId = 2,
  OrderAutoCostRes_FieldNumber_PassengerId = 3,
};

@interface OrderAutoCostRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passengerId;

@end

#pragma mark - OrderPayOkReq

typedef GPB_ENUM(OrderPayOkReq_FieldNumber) {
  OrderPayOkReq_FieldNumber_OrderId = 1,
  OrderPayOkReq_FieldNumber_Cost = 2,
  OrderPayOkReq_FieldNumber_ConnectUser = 3,
};

@interface OrderPayOkReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) double cost;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderPayOkRes

typedef GPB_ENUM(OrderPayOkRes_FieldNumber) {
  OrderPayOkRes_FieldNumber_OrderId = 1,
  OrderPayOkRes_FieldNumber_Cost = 2,
  OrderPayOkRes_FieldNumber_ConnectUser = 3,
};

@interface OrderPayOkRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) double cost;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderPrMissReq

typedef GPB_ENUM(OrderPrMissReq_FieldNumber) {
  OrderPrMissReq_FieldNumber_StartAdd = 1,
  OrderPrMissReq_FieldNumber_EndAdd = 2,
  OrderPrMissReq_FieldNumber_OrderId = 3,
  OrderPrMissReq_FieldNumber_Time = 4,
  OrderPrMissReq_FieldNumber_Content = 5,
  OrderPrMissReq_FieldNumber_StartTime = 6,
  OrderPrMissReq_FieldNumber_ConnectUser = 7,
};

@interface OrderPrMissReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) uint64_t startTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - OrderPrMissRes

typedef GPB_ENUM(OrderPrMissRes_FieldNumber) {
  OrderPrMissRes_FieldNumber_StartAdd = 1,
  OrderPrMissRes_FieldNumber_EndAdd = 2,
  OrderPrMissRes_FieldNumber_OrderId = 3,
  OrderPrMissRes_FieldNumber_Time = 4,
  OrderPrMissRes_FieldNumber_Content = 5,
  OrderPrMissRes_FieldNumber_StartTime = 6,
  OrderPrMissRes_FieldNumber_ConnectUser = 7,
};

@interface OrderPrMissRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *startAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *endAdd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) uint64_t startTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectUser;

@end

#pragma mark - DrstatusWebReq

typedef GPB_ENUM(DrstatusWebReq_FieldNumber) {
  DrstatusWebReq_FieldNumber_DriverId = 1,
};

@interface DrstatusWebReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *driverId;

@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_MsgType = 1,
  Request_FieldNumber_ClientType = 2,
  Request_FieldNumber_ClientId = 3,
  Request_FieldNumber_PhoneType = 4,
  Request_FieldNumber_Ping = 5,
  Request_FieldNumber_LocationReq = 6,
  Request_FieldNumber_RegisterReq = 7,
  Request_FieldNumber_OrderReq = 8,
  Request_FieldNumber_OrderRecReq = 9,
  Request_FieldNumber_OrderAssignReq = 10,
  Request_FieldNumber_OrderDriverArriveReq = 11,
  Request_FieldNumber_OrderDriverPickUpReq = 12,
  Request_FieldNumber_OrderRecEndReq = 13,
  Request_FieldNumber_OrderStartReq = 14,
  Request_FieldNumber_OrderEndReq = 15,
  Request_FieldNumber_OrderPayOkReq = 16,
  Request_FieldNumber_OrderCancelReq = 17,
  Request_FieldNumber_OrderAutoCostReq = 18,
  Request_FieldNumber_UserTrackReq = 19,
  Request_FieldNumber_DrstatusReq = 20,
  Request_FieldNumber_OrderPrMissReq = 21,
  Request_FieldNumber_DrstatusWebReq = 22,
};

typedef GPB_ENUM(Request_Pack_OneOfCase) {
  Request_Pack_OneOfCase_GPBUnsetOneOfCase = 0,
  Request_Pack_OneOfCase_Ping = 5,
  Request_Pack_OneOfCase_LocationReq = 6,
  Request_Pack_OneOfCase_RegisterReq = 7,
  Request_Pack_OneOfCase_OrderReq = 8,
  Request_Pack_OneOfCase_OrderRecReq = 9,
  Request_Pack_OneOfCase_OrderAssignReq = 10,
  Request_Pack_OneOfCase_OrderDriverArriveReq = 11,
  Request_Pack_OneOfCase_OrderDriverPickUpReq = 12,
  Request_Pack_OneOfCase_OrderRecEndReq = 13,
  Request_Pack_OneOfCase_OrderStartReq = 14,
  Request_Pack_OneOfCase_OrderEndReq = 15,
  Request_Pack_OneOfCase_OrderPayOkReq = 16,
  Request_Pack_OneOfCase_OrderCancelReq = 17,
  Request_Pack_OneOfCase_OrderAutoCostReq = 18,
  Request_Pack_OneOfCase_UserTrackReq = 19,
  Request_Pack_OneOfCase_DrstatusReq = 20,
  Request_Pack_OneOfCase_OrderPrMissReq = 21,
  Request_Pack_OneOfCase_DrstatusWebReq = 22,
};

@interface Request : GPBMessage

@property(nonatomic, readwrite) MSG_TYPE msgType;

@property(nonatomic, readwrite) CLIENT_TYPE clientType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

/** android: 1, iOS: 2, h5: 3 */
@property(nonatomic, readwrite) uint32_t phoneType;

@property(nonatomic, readonly) Request_Pack_OneOfCase packOneOfCase;

/** 服务端心跳响应 */
@property(nonatomic, readwrite, strong, null_resettable) Ping *ping;

@property(nonatomic, readwrite, strong, null_resettable) LocationReq *locationReq;

@property(nonatomic, readwrite, strong, null_resettable) RegisterReq *registerReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderReq *orderReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderRecReq *orderRecReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderAssignReq *orderAssignReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderDriverArriveReq *orderDriverArriveReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderDriverPickUpReq *orderDriverPickUpReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderRecEndReq *orderRecEndReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderStartReq *orderStartReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderEndReq *orderEndReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderPayOkReq *orderPayOkReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderCancelReq *orderCancelReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderAutoCostReq *orderAutoCostReq;

@property(nonatomic, readwrite, strong, null_resettable) UserTrackReq *userTrackReq;

@property(nonatomic, readwrite, strong, null_resettable) DrstatusReq *drstatusReq;

@property(nonatomic, readwrite, strong, null_resettable) OrderPrMissReq *orderPrMissReq;

@property(nonatomic, readwrite, strong, null_resettable) DrstatusWebReq *drstatusWebReq;

@end

/**
 * Fetches the raw value of a @c Request's @c msgType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_MsgType_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c msgType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_MsgType_RawValue(Request *message, int32_t value);

/**
 * Fetches the raw value of a @c Request's @c clientType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_ClientType_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c clientType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_ClientType_RawValue(Request *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'pack'.
 **/
void Request_ClearPackOneOfCase(Request *message);

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_MsgType = 1,
  Response_FieldNumber_RetCode = 2,
  Response_FieldNumber_Result = 3,
  Response_FieldNumber_Pong = 4,
  Response_FieldNumber_LocationRes = 5,
  Response_FieldNumber_RegisterRes = 6,
  Response_FieldNumber_OrderRes = 7,
  Response_FieldNumber_OrderRecRes = 8,
  Response_FieldNumber_OrderAssignRes = 9,
  Response_FieldNumber_OrderDriverArriveRes = 10,
  Response_FieldNumber_OrderDriverPickUpRes = 11,
  Response_FieldNumber_OrderRecEndRes = 12,
  Response_FieldNumber_OrderStartRes = 13,
  Response_FieldNumber_OrderEndRes = 14,
  Response_FieldNumber_OrderPayOkRes = 15,
  Response_FieldNumber_OrderCancelRes = 16,
  Response_FieldNumber_OrderAutoCostRes = 17,
  Response_FieldNumber_UserTrackRes = 18,
  Response_FieldNumber_DrstatusRes = 19,
  Response_FieldNumber_OrderPrMissRes = 20,
};

typedef GPB_ENUM(Response_Pack_OneOfCase) {
  Response_Pack_OneOfCase_GPBUnsetOneOfCase = 0,
  Response_Pack_OneOfCase_Pong = 4,
  Response_Pack_OneOfCase_LocationRes = 5,
  Response_Pack_OneOfCase_RegisterRes = 6,
  Response_Pack_OneOfCase_OrderRes = 7,
  Response_Pack_OneOfCase_OrderRecRes = 8,
  Response_Pack_OneOfCase_OrderAssignRes = 9,
  Response_Pack_OneOfCase_OrderDriverArriveRes = 10,
  Response_Pack_OneOfCase_OrderDriverPickUpRes = 11,
  Response_Pack_OneOfCase_OrderRecEndRes = 12,
  Response_Pack_OneOfCase_OrderStartRes = 13,
  Response_Pack_OneOfCase_OrderEndRes = 14,
  Response_Pack_OneOfCase_OrderPayOkRes = 15,
  Response_Pack_OneOfCase_OrderCancelRes = 16,
  Response_Pack_OneOfCase_OrderAutoCostRes = 17,
  Response_Pack_OneOfCase_UserTrackRes = 18,
  Response_Pack_OneOfCase_DrstatusRes = 19,
  Response_Pack_OneOfCase_OrderPrMissRes = 20,
};

@interface Response : GPBMessage

@property(nonatomic, readwrite) MSG_TYPE msgType;

/** 状态码 */
@property(nonatomic, readwrite) RET_CODE retCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *result;

@property(nonatomic, readonly) Response_Pack_OneOfCase packOneOfCase;

/** 服务端心跳响应 */
@property(nonatomic, readwrite, strong, null_resettable) Pong *pong;

@property(nonatomic, readwrite, strong, null_resettable) LocationRes *locationRes;

@property(nonatomic, readwrite, strong, null_resettable) RegisterRes *registerRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderRes *orderRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderRecRes *orderRecRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderAssignRes *orderAssignRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderDriverArriveRes *orderDriverArriveRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderDriverPickUpRes *orderDriverPickUpRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderRecEndRes *orderRecEndRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderStartRes *orderStartRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderEndRes *orderEndRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderPayOkRes *orderPayOkRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderCancelRes *orderCancelRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderAutoCostRes *orderAutoCostRes;

@property(nonatomic, readwrite, strong, null_resettable) UserTrackRes *userTrackRes;

@property(nonatomic, readwrite, strong, null_resettable) DrstatusRes *drstatusRes;

@property(nonatomic, readwrite, strong, null_resettable) OrderPrMissRes *orderPrMissRes;

@end

/**
 * Fetches the raw value of a @c Response's @c msgType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_MsgType_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c msgType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_MsgType_RawValue(Response *message, int32_t value);

/**
 * Fetches the raw value of a @c Response's @c retCode property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_RetCode_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c retCode property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_RetCode_RawValue(Response *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'pack'.
 **/
void Response_ClearPackOneOfCase(Response *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
